[package]
name = "cosmicverge-shared"
version = "0.0.1"
authors = ["Jonathan Johnson <jon@nilobject.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "*", features = ["v4", "serde"] }
basws-shared = "0.1.0-dev-8"
thiserror = "1"
chrono = { version = "*", features = ["serde"] }

