name: Deploy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          ssh-key: ${{ secrets.BOTSU_PRIVATE_SSH_KEY }}

      - name: Configure environment for CI postgres
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@postgres:$POSTGRES_PORT/postgres" >> .env
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Run migrations on CI postgres
        uses: docker://khonsulabs/cosmicverge-build:latest
        with:
          entrypoint: /migrate.sh

      - name: Run tests
        uses: docker://khonsulabs/cosmicverge-build:latest
        with:
          entrypoint: /test.sh

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    needs: test

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          ssh-key: ${{ secrets.BOTSU_PRIVATE_SSH_KEY }}

      - uses: digitalocean/action-doctl@v2
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.DO_WRITE_API_KEY }}

      - name: Configure environment for CI postgres
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@postgres:$POSTGRES_PORT/postgres" >> .env
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Run migrations on CI postgres
        uses: docker://khonsulabs/cosmicverge-build:latest
        with:
          entrypoint: /migrate.sh

      - name: Build
        uses: docker://khonsulabs/cosmicverge-build:latest
        with:
          entrypoint: /build.sh
          args: ${{ secrets.CLIENT_ENCRYPTION_KEY }}

      - name: Generate docs
        run: |
          cd native
          cargo doc --no-deps

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: native/target/doc/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: main/native/
          clean: true

      - name: Authenticate with DigitalOcean Registry
        run: |
          doctl registry login --expiry-seconds 600

      - name: Publish Docker Image
        run: |
          docker build . -t registry.digitalocean.com/khonsulabs/cosmicverge:sha-$GITHUB_SHA -t registry.digitalocean.com/khonsulabs/cosmicverge:main
          docker push -a registry.digitalocean.com/khonsulabs/cosmicverge

      - name: Update Kubernetes
        run: |
          doctl kubernetes cluster kubeconfig save $CLUSTER_ID

          sed -i s/cosmicverge:main/cosmicverge:sha-$GITHUB_SHA/g kubernetes/production.yml
          kubectl apply -f kubernetes/production.yml
          # Wait for the deployment to finish
          kubectl rollout status deployment/cosmicverge --timeout=120s
        env:
          CLUSTER_ID: ${{ secrets.PRODUCTION_CLUSTER_ID }}

        # This is because each worker sends some static resources. We could deploy the static resources before the new CACHEBUSTER gets deployed
        # but we need to deploy it using a simple SPA wrapper which is kind of annoying. For now, there may be cache confusion while kube updates
        # but we purge the cache afterwards to clean it up
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
