[tasks.wasm-pack-development]
condition = { profiles = ["development"] }
script = [
    "cargo build --target wasm32-unknown-unknown",
    "wasm-bindgen target/wasm32-unknown-unknown/debug/web.wasm --target web --out-dir static/pkg --out-name web --remove-producers-section",
    "wasm-opt -O0 static/pkg/web_bg.wasm -o static/pkg/web_bg.wasm"
]

[tasks.wasm-pack-release]
condition = { profiles = ["release"] }
script = [
    "cargo build --target wasm32-unknown-unknown --release",
    "wasm-bindgen target/wasm32-unknown-unknown/release/web.wasm --target web --out-dir static/pkg --out-name web --remove-producers-section",
    "wasm-opt -Os static/pkg/web_bg.wasm -o static/pkg/web_bg.wasm"
]

[tasks.wasm-pack]
run_task = { name = [
    "wasm-pack-release",
    "wasm-pack-development"
], parallel = true }

[tasks.sass]
script = ["sass sass/styles.sass static/styles.css"]

[tasks.build-wasm]
clear = true # For this project we don't want the default build command
run_task = { name = ["wasm-pack"] }

[tasks.build]
clear = true # For this project we don't want the default build command
run_task = { name = ["build-wasm", "sass"] }

[tasks.watch]
run_task = { name = ["watch-sass", "watch-wasm"], parallel = true }

[tasks.watch-sass]
script = ["sass --watch sass/styles.sass static/styles.css"]

[tasks.watch-wasm]
command = "cargo"
args = [
    "watch",
    "-i",
    "static/index.html",
    "-w",
    "src",
    "-w",
    "../shared",
    "-x",
    "make build-wasm"
]
